name: Deploy Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: nelsonjchen/gh-pages-pelican-action@0.2.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PELICAN_CONFIG_FILE: publishconf.py
